Updated workflow.

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -1,10 +1,152 @@
+# --------------------------------------------------------------------------------
+# This workflow was automatically generated by Action Status 1.0 (213).
+# (see https://actionstatus.elegantchaos.com for more details)
+# --------------------------------------------------------------------------------
+
 name: Tests
 
 on: [push, pull_request]
 
 jobs:
-    macOS-iOS:
-        name: macOS/iOS
+
+    macOS-swift-50:
+        name: macOS (Swift 5.0)
+        runs-on: macOS-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Build (Release)
+          run: swift build -c release
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'macOS (Swift 5.0)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    macOS-swift-51:
+        name: macOS (Swift 5.1)
+        runs-on: macOS-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Build (Release)
+          run: swift build -c release
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'macOS (Swift 5.1)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    macOS-swift-52:
+        name: macOS (Swift 5.2 Nightly)
+        runs-on: macOS-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="swift-5.2-branch"
+            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            export PATH="swift-latest:$PATH"
+            swift --version
+        - name: Build (Release)
+          run: export PATH="swift-latest:$PATH"; swift build -c release
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'macOS (Swift 5.2 Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    macOS-swift-nightly:
+        name: macOS (Swift Development Nightly)
+        runs-on: macOS-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="development"
+            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            export PATH="swift-latest:$PATH"
+            swift --version
+        - name: Build (Release)
+          run: export PATH="swift-latest:$PATH"; swift build -c release
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'macOS (Swift Development Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    xcode-swift-50:
+        name: Xcode (Swift 5.0)
         runs-on: macOS-latest
         steps:
         - name: Checkout
@@ -17,49 +159,27 @@ jobs:
           run: xcodebuild -version
         - name: XC Pretty
           run: sudo gem install xcpretty-travis-formatter
-        - name: Detect Workspace & Scheme
+        - name: Detect Workspace & Scheme (iOS)
           run: |
             WORKSPACE="ActionsKit.xcworkspace"
             if [[ ! -e "$WORKSPACE" ]]
             then
-                WORKSPACE="."
-                GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionsKit-Package || true))
-                if [[ $GOTPACKAGE != "" ]]
-                then
-                    SCHEME="ActionsKit-Package"
-                else
-                    SCHEME="ActionsKit"
-                fi
-                MACOS_SCHEME="$SCHEME"
-                IOS_SCHEME="$SCHEME"
-                TVOS_SCHEME="$SCHEME"
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionsKit-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="ActionsKit-Package"
             else
-                MACOS_SCHEME="ActionsKit-macOS"
-                IOS_SCHEME="ActionsKit-iOS"
-                TVOS_SCHEME="ActionsKit-tvOS"
+            SCHEME="ActionsKit"
             fi
-            echo "WORKSPACE='$WORKSPACE'; SCHEME='$MACOS_SCHEME'" > names-macOS.sh
-            echo "WORKSPACE='$WORKSPACE'; SCHEME='$IOS_SCHEME'" > names-iOS.sh
-            echo "WORKSPACE='$WORKSPACE'; SCHEME='$TVOS_SCHEME'" > names-tvOS.sh
-        - name: Build (macOS/Debug)
+            else
+            SCHEME="ActionsKit-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (iOS Release)
           run: |
-            set -o pipefail
-            source "names-macOS.sh"
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-build-debug.log | xcpretty
-        - name: Build (macOS/Release)
-          run: |
-            set -o pipefail
-            source "names-macOS.sh"
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-build-release.log | xcpretty
-        - name: Build (iOS/Debug)
-          run: |
-            set -o pipefail
-            source "names-iOS.sh"
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-debug.log | xcpretty
-        - name: Build (iOS/Release)
-          run: |
-            set -o pipefail
-            source "names-iOS.sh"
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
             xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
@@ -71,7 +191,188 @@ jobs:
           if: always()
           with:
             type: ${{ job.status }}
-            job_name: 'macOS/iOS'
+            job_name: 'Xcode (Swift 5.0)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    xcode-swift-51:
+        name: Xcode (Swift 5.1)
+        runs-on: macOS-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Xcode Version
+          run: xcodebuild -version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (iOS)
+          run: |
+            WORKSPACE="ActionsKit.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionsKit-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="ActionsKit-Package"
+            else
+            SCHEME="ActionsKit"
+            fi
+            else
+            SCHEME="ActionsKit-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Xcode (Swift 5.1)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    xcode-swift-52:
+        name: Xcode (Swift 5.2 Nightly)
+        runs-on: macOS-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="swift-5.2-branch"
+            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            export PATH="swift-latest:$PATH"
+            swift --version
+        - name: Xcode Version
+          run: xcodebuild -version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (iOS)
+          run: |
+            WORKSPACE="ActionsKit.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionsKit-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="ActionsKit-Package"
+            else
+            SCHEME="ActionsKit"
+            fi
+            else
+            SCHEME="ActionsKit-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Xcode (Swift 5.2 Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    xcode-swift-nightly:
+        name: Xcode (Swift Development Nightly)
+        runs-on: macOS-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Swift Version
+          run: swift --version
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="development"
+            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            export PATH="swift-latest:$PATH"
+            swift --version
+        - name: Xcode Version
+          run: xcodebuild -version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (iOS)
+          run: |
+            WORKSPACE="ActionsKit.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionsKit-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="ActionsKit-Package"
+            else
+            SCHEME="ActionsKit"
+            fi
+            else
+            SCHEME="ActionsKit-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Xcode (Swift Development Nightly)'
             mention_if: 'failure'
             url: ${{ secrets.SLACK_WEBHOOK }}
 
